f

diff --git a/.github/workflows/update_workflow.yaml b/.github/workflows/update_workflow.yaml
--- a/.github/workflows/update_workflow.yaml
+++ b/.github/workflows/update_workflow.yaml
@@ -24,37 +24,47 @@ jobs:
       - name: Publish to Marketplace
         run: |
           echo "starting for loop"
-          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.ssp$'); do          
-            echo "file: $file"
-            repo=$(dirname "$file")
-            echo "repo: $repo"
-            manifest_file="manifest.json"
-            iconImage="logo.png"
-            
-            if [ -f "$manifest_file" ]; then
-              echo "performing ls on repo"
-              type=$(jq -r '.schema' "$manifest_file" | cut -d'/' -f1)
-              name=$(jq -r '.name' "$manifest_file")
-              title=$(jq -r '.title' "$manifest_file")
-              description=$(jq -r '.description' "$manifest_file")
-              version=$(jq -r '.version' "$manifest_file")
-              iconImage=$(jq -r '.iconImage' "$manifest_file")
-              
-              if [ -z "$repo" ] || [ -z "$type" ] || [ -z "$name" ] || [ -z "$title" ] || [ -z "$description" ] || [ -z "$version" ] || [ -z "$iconImage" ]; then
-                  echo "Error: One or more required fields are empty or not found in $manifest_file"
-                  exit 1
-              fi
+          changed_files=$(git diff --name-only HEAD~1 HEAD)
 
-              if [ -n "$repo_dir" ]; then
-                echo "running publish script"
-                python publish.py --repo-dir "$repo" --title "$title" --name "$name" --title "$title" --description "$description" --type "$type" --version "$version" --logo "$iconImage"
-              else
-                echo "Repo directory not found in $manifest_file"
-              fi
-            else
-              echo "Manifest file not found in $folder_path"
+          for file in $changed_files; do
+            if [[ $file == *.ssp ]]; then
+              echo "file: $file"
+              folder=$(dirname "$file")
+              echo "folder: $folder"
             fi
           done
+
+          # for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.ssp$'); do          
+          #   echo "file: $file"
+          #   repo=$(dirname "$file")
+          #   echo "repo: $repo"
+          #   manifest_file="manifest.json"
+          #   iconImage="logo.png"
+            
+          #   if [ -f "$manifest_file" ]; then
+          #     echo "performing ls on repo"
+          #     type=$(jq -r '.schema' "$manifest_file" | cut -d'/' -f1)
+          #     name=$(jq -r '.name' "$manifest_file")
+          #     title=$(jq -r '.title' "$manifest_file")
+          #     description=$(jq -r '.description' "$manifest_file")
+          #     version=$(jq -r '.version' "$manifest_file")
+          #     iconImage=$(jq -r '.iconImage' "$manifest_file")
+              
+          #     if [ -z "$repo" ] || [ -z "$type" ] || [ -z "$name" ] || [ -z "$title" ] || [ -z "$description" ] || [ -z "$version" ] || [ -z "$iconImage" ]; then
+          #         echo "Error: One or more required fields are empty or not found in $manifest_file"
+          #         exit 1
+          #     fi
+
+          #     if [ -n "$repo_dir" ]; then
+          #       echo "running publish script"
+          #       python publish.py --repo-dir "$repo" --title "$title" --name "$name" --title "$title" --description "$description" --type "$type" --version "$version" --logo "$iconImage"
+          #     else
+          #       echo "Repo directory not found in $manifest_file"
+          #     fi
+          #   else
+          #     echo "Manifest file not found in $folder_path"
+          #   fi
+          # done
 
       - name: Commit changes
         run: |
