publish

diff --git a/.github/workflows/update_workflow.yaml b/.github/workflows/update_workflow.yaml
--- a/.github/workflows/update_workflow.yaml
+++ b/.github/workflows/update_workflow.yaml
@@ -43,60 +43,35 @@ jobs:
               folder=$(dirname "$file")
               echo "folder: $folder"
               manifest_file="manifest.json"   
-              # convert "$iconImage" -resize 240x240! "$iconImage"
-              # find . -type f \( -iname \*.jpg -o -iname \*.png \) -exec convert {} -resize 240x240! {} \;        
               if [ -f "$manifest_file" ]; then
-                echo "inside manifest"
                 type=$(jq -r '.schema' "$manifest_file" | cut -d'/' -f1)
                 name=$(jq -r '.name' "$manifest_file")
                 title=$(jq -r '.title' "$manifest_file")
                 description=$(jq -r '.description' "$manifest_file")
                 version=$(jq -r '.version' "$manifest_file")
 
-                echo "$type : $name : $title : $description : $version"
+                logo="$folder/logo.png"
+                if [[ -f "$logo" ]]; then
+                  # Resize logo.png to 240x240 pixels
+                  convert "$logo" -resize 240x240! "$logo"
+                  echo "Resized logo.png to 240x240 pixels"
+                else
+                  echo "Current Working Directory: $(pwd)"
+                  echo "logo.png not found in $folder"
+                  echo "Listing files in $folder:"
+                  ls -lah "$folder"
+                  exit 1
+                fi
                 
                 if [ -z "$repo" ] || [ -z "$type" ] || [ -z "$name" ] || [ -z "$title" ] || [ -z "$description" ] || [ -z "$version" ] ; then
                     echo "Error: One or more required fields are empty or not found in $manifest_file"
                     exit 1
                 fi
               fi
-
-              logo="$folder/logo.png"
-              if [[ -f "$logo" ]]; then
-                # Resize logo.png to 240x240 pixels
-                convert "$logo" -resize 240x240! "$logo"
-                echo "Resized logo.png to 240x240 pixels"
-              else
-                  echo "Current Working Directory: $(pwd)"
-                  echo "logo.png not found in $folder"
-                  echo "Listing files in $folder:"
-                  ls -lah "$folder"
-              fi
-
+            python publish.py --repo-dir "$folder" --title "$title" --name "$name" --title "$title" --description "$description" --type "$type" --version "$version" --logo "$logo"
             fi
-          done
-
-        
-          
+          done          
           IFS="$original_ifs"
-
-
-
-          # for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.ssp$'); do          
-          #   echo "file: $file"
-          #   repo=$(dirname "$file")
-          #   echo "repo: $repo"
-
-          #     if [ -n "$repo_dir" ]; then
-          #       echo "running publish script"
-          #       python publish.py --repo-dir "$repo" --title "$title" --name "$name" --title "$title" --description "$description" --type "$type" --version "$version" --logo "$iconImage"
-          #     else
-          #       echo "Repo directory not found in $manifest_file"
-          #     fi
-          #   else
-          #     echo "Manifest file not found in $folder_path"
-          #   fi
-          # done
 
       - name: Commit changes
         run: |
